/**
data x;
set Cpl_1_20220617000123;
if (missing(EPH_LINK_ID) and missing(PRSN_SSK_4)   ) and (missing(SPCLT_PTNT_ID)) and ( missing(SPCLT_PTNT_GID) ) ;
run;

**/

/**



data cpl_1_20220618000123;
length OPP_COL_START OPPTY_EVNT_ID OPPTY_SRC_CD EXTNL_SYS_OPPTY_ID OPPORTUNITY_TYPE_CD 
OPPORTUNITY_SUB_TYPE_CD PGM_ID ALT_OPPTY_SUBTYP_CD ALT_OPPTY_SUBTYP_SRC_CD OPPTY_ACTION_IND OPPTY_STUS_CD OPPTY_CMPGN_ID 
DSESE_CONDTN_NM COMORBD_DSESE_NM OPPTY_CTGRY ENGMNT_ID ENGMNT_VER_ID ENGMNT_PKG_ID KEY_CODE TTL_MBR_SVNGS TTL_CLT_SVNGS 
TTL_MBR_TIME_SVNGS MBR_30D_RTL_COPAY MBR_90D_MAIL_COPAY MBR_QTR_3OD_RTL_COPAY MBR_QTR_SVNGS MSG_COL_START MSG_EVNT_ID MSG_EFF_DT 
MSG_EXPRN_DT CHNL_CD MSG_STUS_CD MSG_STUS_RSN_CD PRTY_NBR MSG_PRDCT_ALT_ID HDR_TXT_ID FTR_TXT_ID LOGO_ID CALL_CNTR_PHN_NBR 
SIGN_LINE_TXT_ID DSCLMR_TXT_ID VRBGE_PRGPH_ID1 VRBGE_PRGPH_ID2 VRBGE_PRGPH_ID3 VRBGE_PRGPH_ID4 VRBGE_PRGPH_ID5 PICTR_ID 
JHNSN_BOX_ID HIPAA_PRVCY_TXT_ID EVNT_PTY_ROLE_CD FUTURE_USE5 FUTURE_USE6 OPPTY_ALTID_TYP_CD OPPTY_TYP_PROD_ID 
OPPTY_CMPGN_REQUEST_ID COMM_GENERATE_DT PRSN_COL_START PRSN_SRC_CD EXTNL_IND EPH_LINK_ID PRSN_SSK_1 PRSN_SSK_2 PRSN_SSK_3 
PRSN_SSK_4 PRSN_SSK_5 PRTC_ID EDW_MBR_GID EXTNL_MBR_ID PGM_ELIG_TYPE_1 PGM_ELIG_IND_1 PGM_ELIG_TYPE_2 PGM_ELIG_IND_2 
PGM_ELIG_TYPE_3 PGM_ELIG_IND_3 PGM_ELIG_TYPE_4 PGM_ELIG_IND_4 PGM_ELIG_TYPE_5 PGM_ELIG_IND_5 CLT_TYP CLT_SRC_CD QL_CLT_ID CLT_NM 
CLT_LEVEL_1 CLT_LEVEL_2 CLT_LEVEL_3 CLT_LEVEL_4 CLT_LEVEL_5 CLT_LEVEL_6 CLT_LEVEL_7 PLAN_NM CLT_BNFT_PLAN_ID CLT_MDCR_IND PAYER_ID 
PTNT_FIRST_NM PTNT_MIDDLE_NM PTNT_LAST_NM PTNT_BRTH_DT PTNT_GNDR_CD PTNT_DOMESTIC_ADDR_IND PTNT_ADDR_LINE1_TX PTNT_ADDR_LINE2_TX 
PTNT_CITY_TX PTNT_STATE_CD PTNT_ZIP_CD PTNT_ZIP_SFX_CD PTNT_COUNTRY_CD PTNT_POSTAL_CD PTNT_TZ PTNT_PHONE1_NBR PTNT_PHONE1_TYP_CD 
PTNT_PHONE2_NBR PTNT_PHONE2_TYP_CD PTNT_EMAIL_ADDR_TX PTNT_EMAIL_TYP_CD PTNT_FAX_NB PTNT_LANG_CD CMK_MAIL_USR_IND MBR_PLAN_TYPE 
RECYCLED_IND MBR_MDCR_IND PRSN_CVS_STORE_NBR PRSN_CMK_PTL_PIN_NBR PRMRY_RX_BNFT_PLAN_CD PRMRY_RX_BNFT_PLAN_TYP 
SCNDRY_RX_BNFT_PLAN_CD SCNDRY_RX_BNFT_PLAN_TYP ADT_PGM_MBR_CPF_ID PTY_ROLE_CD PGM_TYP_CD CLIENT_URL CLIENT_PHONE PTNT_MINOR_IND 
FUTURE_USE14 FUTURE_USE15 PRSC_COL_START PRSC_ID PRSC_NPI_ID PRSC_DEA_NBR PRSC_FIRST_NM PRSC_MIDDLE_NM PRSC_LAST_NM 
PRSC_DOMESTIC_ADDR_IND PRSC_ADDR_LINE1_TX PRSC_ADDR_LINE2_TX PRSC_CITY_TX PRSC_STATE_CD PRSC_ZIP_CD PRSC_ZIP_SFX_CD PRSC_COUNTRY_CD 
PRSC_POSTAL_CD PRSC_TZ PRSC_PHONE1_NBR PRSC_PHONE1_TYP_CD PRSC_PHONE2_NBR PRSC_PHONE2_TYP_CD PRSC_EMAIL_ADDR_TX PRSC_EMAIL_TYP_CD 
PRSC_FAX_NB PRSC_LANG_CD FUTURE_USE16 FUTURE_USE17 FUTURE_USE18 FUTURE_USE19 PHCY_COL_START PHCY_TYPE PHCY_ID PHCY_NM 
PHCY_DOMESTIC_ADDR_IND PHCY_ADDR_LINE1_TX PHCY_ADDR_LINE2_TX PHCY_CITY_TX PHCY_STATE_CD PHCY_ZIP_CD PHCY_ZIP_SFX_CD PHCY_COUNTRY_CD 
PHCY_POSTAL_CD PHCY_TZ PHCY_PHONE1_NBR PHCY_PHONE1_TYP_CD PHCY_PHONE2_NBR PHCY_PHONE2_TYP_CD PHCY_EMAIL_ADDR_TX PHCY_EMAIL_TYP_CD 
PHCY_FAX_NB PHCY_LANG_CD FUTURE_USE20 FUTURE_USE21 FUTURE_USE22 FUTURE_USE23 WAIVR_COL_START WAIVR_CMPGN_ID WAIVR_EFF_DT 
WAIVR_EXPRN_DT EXTNL_CMPGN_IND INCNT_TYP_CD INCNT_DSC WAIVER_AVAIL_CHANNELS DEDTBL_IND PCT_OF_COPAY COPAY_WAIVR_FILL_NBR 
COPAY_WAIVR_AMT DAY_SPLY_QTY WAIVR_AMT NBR_OF_FILL_CNT PCT_MIN_WAIVR_AMT PCT_MAX_WAIVR_AMT WAIVR_DRTN_DAY FUTURE_USE24 FUTURE_USE25 
FUTURE_USE26 FUTURE_USE27 FUTURE_USE28 OPTY_PASS_THRU_FLR1_VAL OPTY_PASS_THRU_FLR2_VAL OPTY_PASS_THRU_FLR3_VAL 
OPTY_PASS_THRU_FLR4_VAL OPTY_PASS_THRU_FLR5_VAL OPTY_PASS_THRU_FLR6_VAL OPTY_PASS_THRU_FLR7_VAL OPTY_PASS_THRU_FLR8_VAL 
OPTY_PASS_THRU_FLR9_VAL OPTY_PASS_THRU_FLR10_VAL OPTY_PASS_THRU_FLR11_VAL OPTY_PASS_THRU_FLR12_VAL OPTY_PASS_THRU_FLR13_VAL 
OPTY_PASS_THRU_FLR14_VAL OPTY_PASS_THRU_FLR15_VAL OPTY_PASS_THRU_FLR16_VAL OPTY_PASS_THRU_FLR17_VAL OPTY_PASS_THRU_FLR18_VAL 
OPTY_PASS_THRU_FLR19_VAL OPTY_PASS_THRU_FLR20_VAL MSG_PASS_THRU_FLR1_VAL MSG_PASS_THRU_FLR2_VAL MSG_PASS_THRU_FLR3_VAL 
MSG_PASS_THRU_FLR4_VAL MSG_PASS_THRU_FLR5_VAL MSG_PASS_THRU_FLR6_VAL MSG_PASS_THRU_FLR7_VAL MSG_PASS_THRU_FLR8_VAL 
MSG_PASS_THRU_FLR9_VAL MSG_PASS_THRU_FLR10_VAL MSG_PASS_THRU_FLR11_VAL MSG_PASS_THRU_FLR12_VAL MSG_PASS_THRU_FLR13_VAL 
MSG_PASS_THRU_FLR14_VAL MSG_PASS_THRU_FLR15_VAL MSG_PASS_THRU_FLR16_VAL MSG_PASS_THRU_FLR17_VAL MSG_PASS_THRU_FLR18_VAL 
MSG_PASS_THRU_FLR19_VAL MSG_PASS_THRU_FLR20_VAL OTHER_COL_START TRGT_SCOPE_CD OPPTY_STUS_RSN_CD OPPTY_DISPN_CD OPPTY_DISPN_SUB_CD 
PGM_PROD_ID AGNT_PTY_ID2 NOTE_EVNT_ID NOTE_TX OPPTY_EFF_DT OPPTY_EXPRN_DT OPPTY_DLVRY_IND PGM_TYPE_CD MGRTN_IND MGRTN_TS 
BYPASS_THRSHLD_IND OPPTY_ALTID PRSCRPT_FILL_ID ACTVN_CD MSG_TYP_PROD_ID BYPS_DLVRY_THRSLD_IND PRSTN_IND NOTE_TX2 AGNT_PTY_ID 
CMNCT_TYP_CD ACTN_IND NOTE_EVNT_ID2 MSG_SHRT_DESC COMM_MSG_TXT PTNT_CNSL_STUS_CD PTNT_CNSL_SUB_STUS_CD DLVRY_CHNL_FAC_ID 
EVNT_PTY_ID PTY_ID ACCT_ID EFF_DT EXPRN_DT SRC_CD PTY_ALTID_TYP_CD EVNT_TYP_CD CRDHLDR_PRTC_ID CLNT_ID CLNT_CD PLAN_NBR 
PLAN_EXTNSN_NBR GRP_EXTNSN_NBR BILL_RPT_NBR PRSN_NBR INS_CD CPG_ID RXCONNECT_PTNT_ID MBR_BIRTH_DT MBR_GNDR_CD MBR_LANG_CD 
CLT_AGGR_LIST_ID CLT_AGGR_LIST_NM EVNT_CNTCT_INFO_ID PHA_ELIG_IND RDY_FILL_ELIG_IND CLT_MDCD_IND CLT_URL CLT_PHONE_NBR HIC_NBR 
MBR_ELIG_EFF_DT MBR_ELIG_END_DT CMS_CNTRCT_ID CMS_PLAN_ID QL_PRSC_ID PTNT_ID BIN PCN PRSC_SPI_ID MCHOICE_CNTCT_TYP_CD 
MCHOICE_OPTOUT_CD PRSN_REL_CD SPCLT_PTNT_ID SPCLT_PTNT_SRC_CD SPCLT_PTNT_GID PTNT_SCORE_TYP_CD PTNT_SCORE RXCLAIM_CLNT_CD 
HEALTHPLAN_PROXY_ID HEALTHPLAN_INDIVIDUAL_ID EVNT_PTY_CNTCT_ID ORGANIZATION_NM CONTACT_DATA_TYPE CONTACT_DATA_SOURCE 
ORGANIZATION_ID DIRECT_ADDR_TX MSG_PASS_THRU_FLR1_NM MSG_PASS_THRU_FLR2_NM MSG_PASS_THRU_FLR3_NM MSG_PASS_THRU_FLR4_NM 
MSG_PASS_THRU_FLR5_NM MSG_PASS_THRU_FLR6_NM MSG_PASS_THRU_FLR7_NM MSG_PASS_THRU_FLR8_NM MSG_PASS_THRU_FLR9_NM 
MSG_PASS_THRU_FLR10_NM MSG_PASS_THRU_FLR11_NM MSG_PASS_THRU_FLR12_NM MSG_PASS_THRU_FLR13_NM MSG_PASS_THRU_FLR14_NM 
MSG_PASS_THRU_FLR15_NM MSG_PASS_THRU_FLR16_NM MSG_PASS_THRU_FLR17_NM MSG_PASS_THRU_FLR18_NM MSG_PASS_THRU_FLR19_NM 
MSG_PASS_THRU_FLR20_NM PASS_THRU_FLR1_NM PASS_THRU_FLR2_NM PASS_THRU_FLR3_NM PASS_THRU_FLR4_NM PASS_THRU_FLR5_NM PASS_THRU_FLR6_NM 
PASS_THRU_FLR7_NM PASS_THRU_FLR8_NM PASS_THRU_FLR9_NM PASS_THRU_FLR10_NM PASS_THRU_FLR11_NM PASS_THRU_FLR12_NM PASS_THRU_FLR13_NM 
PASS_THRU_FLR14_NM PASS_THRU_FLR15_NM PASS_THRU_FLR16_NM PASS_THRU_FLR17_NM PASS_THRU_FLR18_NM PASS_THRU_FLR19_NM 
PASS_THRU_FLR20_NM VNDR_CASE_ID PHCY_NCPDP_ID PHCY_NPI_ID REIM_PGM_ID OPPTY_PHCY_PYMT OPPTY_OTCM SVC_STATUS DECLINE_REASON SVC_DT 
PHCY_CLSE_DT ADM_CLSE_RSN EXTNL_DISP_CD CASE_FIRST_VW_DT CASE_CRTN_DT CASE_ASGN_DT OMISSION_CARE_GAP_RLE ALERT_VERIFIED ALERT_TYP 
SUPP_NOTES RECOMMENDATION VNDR_PHCY_RES1 VNDR_PHCY_RES2 VNDR_PHCY_RES3 VNDR_PHCY_RES4 VNDR_PHCY_RES5 VNDR_PHCY_RES6 VNDR_PHCY_RES7 
VNDR_PHCY_RES8 VNDR_PHCY_RES9 VNDR_PHCY_RES10 VNDR_PHCY_RES11 VNDR_PHCY_RES12 VNDR_PHCY_RES13 VNDR_PHCY_RES14 VNDR_PHCY_RES15 
VNDR_PHCY_RES16 VNDR_PHCY_RES17 VNDR_PHCY_RES18 VNDR_PHCY_RES19 VNDR_PHCY_RES20 VNDR_PHCY_RES21 VNDR_PHCY_RES22 VNDR_PHCY_RES23 
VNDR_PHCY_RES24 VNDR_PHCY_RES25 VNDR_PHCY_RES26 VNDR_PHCY_RES27 VNDR_PHCY_RES28 VNDR_PHCY_RES29 VNDR_PHCY_RES30 VNDR_PHCY_RES31 
VNDR_PHCY_RES32 VNDR_PHCY_RES33 VNDR_PHCY_RES34 VNDR_PHCY_RES35 VNDR_PHCY_RES36 VNDR_PHCY_RES37 VNDR_PHCY_RES38 VNDR_PHCY_RES39 
VNDR_PHCY_RES40 VNDR_PHCY_RES41 VNDR_PHCY_RES42 VNDR_PHCY_RES43 VNDR_PHCY_RES44 VNDR_PHCY_RES45 VNDR_PHCY_RES46 VNDR_PHCY_RES47 
VNDR_PHCY_RES48 VNDR_PHCY_RES49 VNDR_PHCY_RES50 VNDR_PHCY_RES51 VNDR_PHCY_RES52 VNDR_PHCY_RES53 VNDR_PHCY_RES54 VNDR_PHCY_RES55 
VNDR_PHCY_RES56 VNDR_PHCY_RES57 VNDR_PHCY_RES58 VNDR_PHCY_RES59 VNDR_PHCY_RES60 VNDR_PHCY_RES61 VNDR_PHCY_RES62 VNDR_PHCY_RES63 
VNDR_PHCY_RES64 VNDR_PHCY_RES65 VNDR_PHCY_RES66 VNDR_PHCY_RES67 VNDR_PHCY_RES68 VNDR_PHCY_RES69 VNDR_PHCY_RES70 VNDR_PHCY_RES71 
VNDR_PHCY_RES72 VNDR_PHCY_RES73 VNDR_PHCY_RES74 VNDR_PHCY_RES75 VNDR_PHCY_RES76 VNDR_PHCY_RES77 VNDR_PHCY_RES78 VNDR_PHCY_RES79 
VNDR_PHCY_RES80 VNDR_PHCY_RES81 VNDR_PHCY_RES82 VNDR_PHCY_RES83 VNDR_PHCY_RES84 VNDR_PHCY_RES85 VNDR_PHCY_RES86 VNDR_PHCY_RES87 
VNDR_PHCY_RES88 VNDR_PHCY_RES89 VNDR_PHCY_RES90 VNDR_PHCY_RES91 VNDR_PHCY_RES92 VNDR_PHCY_RES93 VNDR_PHCY_RES94 VNDR_PHCY_RES95 
VNDR_PHCY_RES96 VNDR_PHCY_RES97 VNDR_PHCY_RES98 VNDR_PHCY_RES99 VNDR_PHCY_RES100 VNDR_PHCY_RES101 VNDR_PHCY_RES102 VNDR_PHCY_RES103 
VNDR_PHCY_RES104 VNDR_PHCY_RES105 VNDR_PHCY_RES106 VNDR_PHCY_RES107 VNDR_PHCY_RES108 VNDR_PHCY_RES109 VNDR_PHCY_RES110 
VNDR_PHCY_RES111 VNDR_PHCY_RES112 VNDR_PHCY_RES113 VNDR_PHCY_RES114 VNDR_PHCY_RES115 VNDR_PHCY_RES116 VNDR_PHCY_RES117 
VNDR_PHCY_RES118 VNDR_PHCY_RES119 VNDR_PHCY_RES120 DFT_PHCY_RES1 DFT_PHCY_RES2 DFT_PHCY_RES3 DFT_PHCY_RES4 DFT_PHCY_RES5 
DFT_PHCY_RES6 DFT_PHCY_RES7 DFT_PHCY_RES8 DFT_PHCY_RES9 DFT_PHCY_RES10 DFT_PHCY_RES11 DFT_PHCY_RES12 DFT_PHCY_RES13 DFT_PHCY_RES14 
DFT_PHCY_RES15 DFT_PHCY_RES16 DFT_PHCY_RES17 DFT_PHCY_RES18 DFT_PHCY_RES19 DFT_PHCY_RES20 DFT_PHCY_RES21 DFT_PHCY_RES22 
DFT_PHCY_RES23 DFT_PHCY_RES24 DFT_PHCY_RES25 DFT_PHCY_RES26 DFT_PHCY_RES27 DFT_PHCY_RES28 DFT_PHCY_RES29 DFT_PHCY_RES30 
DFT_PHCY_RES31 DFT_PHCY_RES32 DFT_PHCY_RES33 DFT_PHCY_RES34 DFT_PHCY_RES35 DFT_PHCY_RES36 DFT_PHCY_RES37 DFT_PHCY_RES38 
DFT_PHCY_RES39 DFT_PHCY_RES40 DFT_PHCY_RES41 DFT_PHCY_RES42 DFT_PHCY_RES43 DFT_PHCY_RES44 DFT_PHCY_RES45 DFT_PHCY_RES46 
DFT_PHCY_RES47 DFT_PHCY_RES48 DFT_PHCY_RES49 DFT_PHCY_RES50 SVC_TRANS_ID BILL_PROCESS_DT CAMPAIGN_ID NON_PBM_CLNT_ID SRC_CD2 
REV_TYP_ACCOUNT LINE_ITEM_TYPE OPPTY_SUBTYP_CD DLVRY_CHANNEL DLVRY_OPTION QUANTITY RATE TOTAL_BILLAMT PROCESS_FLG ERROR_CD 
ERROR_DESC ACCT_TYP_CD OPPTY_ALTID2 BILL_DT CHANNEL OPPTY_CMPGN_CD CAMPAIGN_DESC CMPGN_TYP OPPTY_SUBTYP_ID OPPTY_SUBTYP_CD2 
BILL_TYPE RATE_BILLED SRC_CD3 BO_CLIENT DCS_CLIENT CLNT_AGGR_LST_NM NON_PBM_CLNT_ID2 EVNT_REL_ID ERROR_CD2 QL_BENE_ID PRSN_NBR2 
EXT_MEMBER_ID CHNL_REC_STATUS CHNL_REC_CREATED_DT CHNL_REC_DLVRY_DT CHNL_REC_DISPOSITION_DT ERROR_CD3 ERROR_DESC2 ACCT_TYP_CD2 
EVNT_PROD_ID PROD_ID WAIVR_CMPGN_EFF_DT WAIVR_CMPGN_EXP_DT WAIVR_DSC_TX WAIVR_CLM_SRC_XREF_ID REC_CRTE_PROC_ID REC_CRTE_TRANS_ID 
REC_CRTE_TS REC_CRTE_USER_ID REC_SRC_FILE_NM REC_UPD_PROC_ID REC_UPD_TRANS_ID REC_UPD_TS REC_UPD_USER_ID $100. ;
infile "C:\Users\BStropich1\Documents\Brian\team_AZ\project_stars\CTR000000 - 2019 projects\83_2021_blue_chips_eoca\12_sftp_files\12_cpl_20220618\cpl_opportunity.20220618110039" firstobs=1 
missover pad lrecl=32000 delimiter='|' dsd;
input OPP_COL_START OPPTY_EVNT_ID OPPTY_SRC_CD EXTNL_SYS_OPPTY_ID OPPORTUNITY_TYPE_CD 
OPPORTUNITY_SUB_TYPE_CD PGM_ID ALT_OPPTY_SUBTYP_CD ALT_OPPTY_SUBTYP_SRC_CD OPPTY_ACTION_IND OPPTY_STUS_CD OPPTY_CMPGN_ID 
DSESE_CONDTN_NM COMORBD_DSESE_NM OPPTY_CTGRY ENGMNT_ID ENGMNT_VER_ID ENGMNT_PKG_ID KEY_CODE TTL_MBR_SVNGS TTL_CLT_SVNGS 
TTL_MBR_TIME_SVNGS MBR_30D_RTL_COPAY MBR_90D_MAIL_COPAY MBR_QTR_3OD_RTL_COPAY MBR_QTR_SVNGS MSG_COL_START MSG_EVNT_ID MSG_EFF_DT 
MSG_EXPRN_DT CHNL_CD MSG_STUS_CD MSG_STUS_RSN_CD PRTY_NBR MSG_PRDCT_ALT_ID HDR_TXT_ID FTR_TXT_ID LOGO_ID CALL_CNTR_PHN_NBR 
SIGN_LINE_TXT_ID DSCLMR_TXT_ID VRBGE_PRGPH_ID1 VRBGE_PRGPH_ID2 VRBGE_PRGPH_ID3 VRBGE_PRGPH_ID4 VRBGE_PRGPH_ID5 PICTR_ID 
JHNSN_BOX_ID HIPAA_PRVCY_TXT_ID EVNT_PTY_ROLE_CD FUTURE_USE5 FUTURE_USE6 OPPTY_ALTID_TYP_CD OPPTY_TYP_PROD_ID 
OPPTY_CMPGN_REQUEST_ID COMM_GENERATE_DT PRSN_COL_START PRSN_SRC_CD EXTNL_IND EPH_LINK_ID PRSN_SSK_1 PRSN_SSK_2 PRSN_SSK_3 
PRSN_SSK_4 PRSN_SSK_5 PRTC_ID EDW_MBR_GID EXTNL_MBR_ID PGM_ELIG_TYPE_1 PGM_ELIG_IND_1 PGM_ELIG_TYPE_2 PGM_ELIG_IND_2 
PGM_ELIG_TYPE_3 PGM_ELIG_IND_3 PGM_ELIG_TYPE_4 PGM_ELIG_IND_4 PGM_ELIG_TYPE_5 PGM_ELIG_IND_5 CLT_TYP CLT_SRC_CD QL_CLT_ID CLT_NM 
CLT_LEVEL_1 CLT_LEVEL_2 CLT_LEVEL_3 CLT_LEVEL_4 CLT_LEVEL_5 CLT_LEVEL_6 CLT_LEVEL_7 PLAN_NM CLT_BNFT_PLAN_ID CLT_MDCR_IND PAYER_ID 
PTNT_FIRST_NM PTNT_MIDDLE_NM PTNT_LAST_NM PTNT_BRTH_DT PTNT_GNDR_CD PTNT_DOMESTIC_ADDR_IND PTNT_ADDR_LINE1_TX PTNT_ADDR_LINE2_TX 
PTNT_CITY_TX PTNT_STATE_CD PTNT_ZIP_CD PTNT_ZIP_SFX_CD PTNT_COUNTRY_CD PTNT_POSTAL_CD PTNT_TZ PTNT_PHONE1_NBR PTNT_PHONE1_TYP_CD 
PTNT_PHONE2_NBR PTNT_PHONE2_TYP_CD PTNT_EMAIL_ADDR_TX PTNT_EMAIL_TYP_CD PTNT_FAX_NB PTNT_LANG_CD CMK_MAIL_USR_IND MBR_PLAN_TYPE 
RECYCLED_IND MBR_MDCR_IND PRSN_CVS_STORE_NBR PRSN_CMK_PTL_PIN_NBR PRMRY_RX_BNFT_PLAN_CD PRMRY_RX_BNFT_PLAN_TYP 
SCNDRY_RX_BNFT_PLAN_CD SCNDRY_RX_BNFT_PLAN_TYP ADT_PGM_MBR_CPF_ID PTY_ROLE_CD PGM_TYP_CD CLIENT_URL CLIENT_PHONE PTNT_MINOR_IND 
FUTURE_USE14 FUTURE_USE15 PRSC_COL_START PRSC_ID PRSC_NPI_ID PRSC_DEA_NBR PRSC_FIRST_NM PRSC_MIDDLE_NM PRSC_LAST_NM 
PRSC_DOMESTIC_ADDR_IND PRSC_ADDR_LINE1_TX PRSC_ADDR_LINE2_TX PRSC_CITY_TX PRSC_STATE_CD PRSC_ZIP_CD PRSC_ZIP_SFX_CD PRSC_COUNTRY_CD 
PRSC_POSTAL_CD PRSC_TZ PRSC_PHONE1_NBR PRSC_PHONE1_TYP_CD PRSC_PHONE2_NBR PRSC_PHONE2_TYP_CD PRSC_EMAIL_ADDR_TX PRSC_EMAIL_TYP_CD 
PRSC_FAX_NB PRSC_LANG_CD FUTURE_USE16 FUTURE_USE17 FUTURE_USE18 FUTURE_USE19 PHCY_COL_START PHCY_TYPE PHCY_ID PHCY_NM 
PHCY_DOMESTIC_ADDR_IND PHCY_ADDR_LINE1_TX PHCY_ADDR_LINE2_TX PHCY_CITY_TX PHCY_STATE_CD PHCY_ZIP_CD PHCY_ZIP_SFX_CD PHCY_COUNTRY_CD 
PHCY_POSTAL_CD PHCY_TZ PHCY_PHONE1_NBR PHCY_PHONE1_TYP_CD PHCY_PHONE2_NBR PHCY_PHONE2_TYP_CD PHCY_EMAIL_ADDR_TX PHCY_EMAIL_TYP_CD 
PHCY_FAX_NB PHCY_LANG_CD FUTURE_USE20 FUTURE_USE21 FUTURE_USE22 FUTURE_USE23 WAIVR_COL_START WAIVR_CMPGN_ID WAIVR_EFF_DT 
WAIVR_EXPRN_DT EXTNL_CMPGN_IND INCNT_TYP_CD INCNT_DSC WAIVER_AVAIL_CHANNELS DEDTBL_IND PCT_OF_COPAY COPAY_WAIVR_FILL_NBR 
COPAY_WAIVR_AMT DAY_SPLY_QTY WAIVR_AMT NBR_OF_FILL_CNT PCT_MIN_WAIVR_AMT PCT_MAX_WAIVR_AMT WAIVR_DRTN_DAY FUTURE_USE24 FUTURE_USE25 
FUTURE_USE26 FUTURE_USE27 FUTURE_USE28 OPTY_PASS_THRU_FLR1_VAL OPTY_PASS_THRU_FLR2_VAL OPTY_PASS_THRU_FLR3_VAL 
OPTY_PASS_THRU_FLR4_VAL OPTY_PASS_THRU_FLR5_VAL OPTY_PASS_THRU_FLR6_VAL OPTY_PASS_THRU_FLR7_VAL OPTY_PASS_THRU_FLR8_VAL 
OPTY_PASS_THRU_FLR9_VAL OPTY_PASS_THRU_FLR10_VAL OPTY_PASS_THRU_FLR11_VAL OPTY_PASS_THRU_FLR12_VAL OPTY_PASS_THRU_FLR13_VAL 
OPTY_PASS_THRU_FLR14_VAL OPTY_PASS_THRU_FLR15_VAL OPTY_PASS_THRU_FLR16_VAL OPTY_PASS_THRU_FLR17_VAL OPTY_PASS_THRU_FLR18_VAL 
OPTY_PASS_THRU_FLR19_VAL OPTY_PASS_THRU_FLR20_VAL MSG_PASS_THRU_FLR1_VAL MSG_PASS_THRU_FLR2_VAL MSG_PASS_THRU_FLR3_VAL 
MSG_PASS_THRU_FLR4_VAL MSG_PASS_THRU_FLR5_VAL MSG_PASS_THRU_FLR6_VAL MSG_PASS_THRU_FLR7_VAL MSG_PASS_THRU_FLR8_VAL 
MSG_PASS_THRU_FLR9_VAL MSG_PASS_THRU_FLR10_VAL MSG_PASS_THRU_FLR11_VAL MSG_PASS_THRU_FLR12_VAL MSG_PASS_THRU_FLR13_VAL 
MSG_PASS_THRU_FLR14_VAL MSG_PASS_THRU_FLR15_VAL MSG_PASS_THRU_FLR16_VAL MSG_PASS_THRU_FLR17_VAL MSG_PASS_THRU_FLR18_VAL 
MSG_PASS_THRU_FLR19_VAL MSG_PASS_THRU_FLR20_VAL OTHER_COL_START TRGT_SCOPE_CD OPPTY_STUS_RSN_CD OPPTY_DISPN_CD OPPTY_DISPN_SUB_CD 
PGM_PROD_ID AGNT_PTY_ID2 NOTE_EVNT_ID NOTE_TX OPPTY_EFF_DT OPPTY_EXPRN_DT OPPTY_DLVRY_IND PGM_TYPE_CD MGRTN_IND MGRTN_TS 
BYPASS_THRSHLD_IND OPPTY_ALTID PRSCRPT_FILL_ID ACTVN_CD MSG_TYP_PROD_ID BYPS_DLVRY_THRSLD_IND PRSTN_IND NOTE_TX2 AGNT_PTY_ID 
CMNCT_TYP_CD ACTN_IND NOTE_EVNT_ID2 MSG_SHRT_DESC COMM_MSG_TXT PTNT_CNSL_STUS_CD PTNT_CNSL_SUB_STUS_CD DLVRY_CHNL_FAC_ID 
EVNT_PTY_ID PTY_ID ACCT_ID EFF_DT EXPRN_DT SRC_CD PTY_ALTID_TYP_CD EVNT_TYP_CD CRDHLDR_PRTC_ID CLNT_ID CLNT_CD PLAN_NBR 
PLAN_EXTNSN_NBR GRP_EXTNSN_NBR BILL_RPT_NBR PRSN_NBR INS_CD CPG_ID RXCONNECT_PTNT_ID MBR_BIRTH_DT MBR_GNDR_CD MBR_LANG_CD 
CLT_AGGR_LIST_ID CLT_AGGR_LIST_NM EVNT_CNTCT_INFO_ID PHA_ELIG_IND RDY_FILL_ELIG_IND CLT_MDCD_IND CLT_URL CLT_PHONE_NBR HIC_NBR 
MBR_ELIG_EFF_DT MBR_ELIG_END_DT CMS_CNTRCT_ID CMS_PLAN_ID QL_PRSC_ID PTNT_ID BIN PCN PRSC_SPI_ID MCHOICE_CNTCT_TYP_CD 
MCHOICE_OPTOUT_CD PRSN_REL_CD SPCLT_PTNT_ID SPCLT_PTNT_SRC_CD SPCLT_PTNT_GID PTNT_SCORE_TYP_CD PTNT_SCORE RXCLAIM_CLNT_CD 
HEALTHPLAN_PROXY_ID HEALTHPLAN_INDIVIDUAL_ID EVNT_PTY_CNTCT_ID ORGANIZATION_NM CONTACT_DATA_TYPE CONTACT_DATA_SOURCE 
ORGANIZATION_ID DIRECT_ADDR_TX MSG_PASS_THRU_FLR1_NM MSG_PASS_THRU_FLR2_NM MSG_PASS_THRU_FLR3_NM MSG_PASS_THRU_FLR4_NM 
MSG_PASS_THRU_FLR5_NM MSG_PASS_THRU_FLR6_NM MSG_PASS_THRU_FLR7_NM MSG_PASS_THRU_FLR8_NM MSG_PASS_THRU_FLR9_NM 
MSG_PASS_THRU_FLR10_NM MSG_PASS_THRU_FLR11_NM MSG_PASS_THRU_FLR12_NM MSG_PASS_THRU_FLR13_NM MSG_PASS_THRU_FLR14_NM 
MSG_PASS_THRU_FLR15_NM MSG_PASS_THRU_FLR16_NM MSG_PASS_THRU_FLR17_NM MSG_PASS_THRU_FLR18_NM MSG_PASS_THRU_FLR19_NM 
MSG_PASS_THRU_FLR20_NM PASS_THRU_FLR1_NM PASS_THRU_FLR2_NM PASS_THRU_FLR3_NM PASS_THRU_FLR4_NM PASS_THRU_FLR5_NM PASS_THRU_FLR6_NM 
PASS_THRU_FLR7_NM PASS_THRU_FLR8_NM PASS_THRU_FLR9_NM PASS_THRU_FLR10_NM PASS_THRU_FLR11_NM PASS_THRU_FLR12_NM PASS_THRU_FLR13_NM 
PASS_THRU_FLR14_NM PASS_THRU_FLR15_NM PASS_THRU_FLR16_NM PASS_THRU_FLR17_NM PASS_THRU_FLR18_NM PASS_THRU_FLR19_NM 
PASS_THRU_FLR20_NM VNDR_CASE_ID PHCY_NCPDP_ID PHCY_NPI_ID REIM_PGM_ID OPPTY_PHCY_PYMT OPPTY_OTCM SVC_STATUS DECLINE_REASON SVC_DT 
PHCY_CLSE_DT ADM_CLSE_RSN EXTNL_DISP_CD CASE_FIRST_VW_DT CASE_CRTN_DT CASE_ASGN_DT OMISSION_CARE_GAP_RLE ALERT_VERIFIED ALERT_TYP 
SUPP_NOTES RECOMMENDATION VNDR_PHCY_RES1 VNDR_PHCY_RES2 VNDR_PHCY_RES3 VNDR_PHCY_RES4 VNDR_PHCY_RES5 VNDR_PHCY_RES6 VNDR_PHCY_RES7 
VNDR_PHCY_RES8 VNDR_PHCY_RES9 VNDR_PHCY_RES10 VNDR_PHCY_RES11 VNDR_PHCY_RES12 VNDR_PHCY_RES13 VNDR_PHCY_RES14 VNDR_PHCY_RES15 
VNDR_PHCY_RES16 VNDR_PHCY_RES17 VNDR_PHCY_RES18 VNDR_PHCY_RES19 VNDR_PHCY_RES20 VNDR_PHCY_RES21 VNDR_PHCY_RES22 VNDR_PHCY_RES23 
VNDR_PHCY_RES24 VNDR_PHCY_RES25 VNDR_PHCY_RES26 VNDR_PHCY_RES27 VNDR_PHCY_RES28 VNDR_PHCY_RES29 VNDR_PHCY_RES30 VNDR_PHCY_RES31 
VNDR_PHCY_RES32 VNDR_PHCY_RES33 VNDR_PHCY_RES34 VNDR_PHCY_RES35 VNDR_PHCY_RES36 VNDR_PHCY_RES37 VNDR_PHCY_RES38 VNDR_PHCY_RES39 
VNDR_PHCY_RES40 VNDR_PHCY_RES41 VNDR_PHCY_RES42 VNDR_PHCY_RES43 VNDR_PHCY_RES44 VNDR_PHCY_RES45 VNDR_PHCY_RES46 VNDR_PHCY_RES47 
VNDR_PHCY_RES48 VNDR_PHCY_RES49 VNDR_PHCY_RES50 VNDR_PHCY_RES51 VNDR_PHCY_RES52 VNDR_PHCY_RES53 VNDR_PHCY_RES54 VNDR_PHCY_RES55 
VNDR_PHCY_RES56 VNDR_PHCY_RES57 VNDR_PHCY_RES58 VNDR_PHCY_RES59 VNDR_PHCY_RES60 VNDR_PHCY_RES61 VNDR_PHCY_RES62 VNDR_PHCY_RES63 
VNDR_PHCY_RES64 VNDR_PHCY_RES65 VNDR_PHCY_RES66 VNDR_PHCY_RES67 VNDR_PHCY_RES68 VNDR_PHCY_RES69 VNDR_PHCY_RES70 VNDR_PHCY_RES71 
VNDR_PHCY_RES72 VNDR_PHCY_RES73 VNDR_PHCY_RES74 VNDR_PHCY_RES75 VNDR_PHCY_RES76 VNDR_PHCY_RES77 VNDR_PHCY_RES78 VNDR_PHCY_RES79 
VNDR_PHCY_RES80 VNDR_PHCY_RES81 VNDR_PHCY_RES82 VNDR_PHCY_RES83 VNDR_PHCY_RES84 VNDR_PHCY_RES85 VNDR_PHCY_RES86 VNDR_PHCY_RES87 
VNDR_PHCY_RES88 VNDR_PHCY_RES89 VNDR_PHCY_RES90 VNDR_PHCY_RES91 VNDR_PHCY_RES92 VNDR_PHCY_RES93 VNDR_PHCY_RES94 VNDR_PHCY_RES95 
VNDR_PHCY_RES96 VNDR_PHCY_RES97 VNDR_PHCY_RES98 VNDR_PHCY_RES99 VNDR_PHCY_RES100 VNDR_PHCY_RES101 VNDR_PHCY_RES102 VNDR_PHCY_RES103 
VNDR_PHCY_RES104 VNDR_PHCY_RES105 VNDR_PHCY_RES106 VNDR_PHCY_RES107 VNDR_PHCY_RES108 VNDR_PHCY_RES109 VNDR_PHCY_RES110 
VNDR_PHCY_RES111 VNDR_PHCY_RES112 VNDR_PHCY_RES113 VNDR_PHCY_RES114 VNDR_PHCY_RES115 VNDR_PHCY_RES116 VNDR_PHCY_RES117 
VNDR_PHCY_RES118 VNDR_PHCY_RES119 VNDR_PHCY_RES120 DFT_PHCY_RES1 DFT_PHCY_RES2 DFT_PHCY_RES3 DFT_PHCY_RES4 DFT_PHCY_RES5 
DFT_PHCY_RES6 DFT_PHCY_RES7 DFT_PHCY_RES8 DFT_PHCY_RES9 DFT_PHCY_RES10 DFT_PHCY_RES11 DFT_PHCY_RES12 DFT_PHCY_RES13 DFT_PHCY_RES14 
DFT_PHCY_RES15 DFT_PHCY_RES16 DFT_PHCY_RES17 DFT_PHCY_RES18 DFT_PHCY_RES19 DFT_PHCY_RES20 DFT_PHCY_RES21 DFT_PHCY_RES22 
DFT_PHCY_RES23 DFT_PHCY_RES24 DFT_PHCY_RES25 DFT_PHCY_RES26 DFT_PHCY_RES27 DFT_PHCY_RES28 DFT_PHCY_RES29 DFT_PHCY_RES30 
DFT_PHCY_RES31 DFT_PHCY_RES32 DFT_PHCY_RES33 DFT_PHCY_RES34 DFT_PHCY_RES35 DFT_PHCY_RES36 DFT_PHCY_RES37 DFT_PHCY_RES38 
DFT_PHCY_RES39 DFT_PHCY_RES40 DFT_PHCY_RES41 DFT_PHCY_RES42 DFT_PHCY_RES43 DFT_PHCY_RES44 DFT_PHCY_RES45 DFT_PHCY_RES46 
DFT_PHCY_RES47 DFT_PHCY_RES48 DFT_PHCY_RES49 DFT_PHCY_RES50 SVC_TRANS_ID BILL_PROCESS_DT CAMPAIGN_ID NON_PBM_CLNT_ID SRC_CD2 
REV_TYP_ACCOUNT LINE_ITEM_TYPE OPPTY_SUBTYP_CD DLVRY_CHANNEL DLVRY_OPTION QUANTITY RATE TOTAL_BILLAMT PROCESS_FLG ERROR_CD 
ERROR_DESC ACCT_TYP_CD OPPTY_ALTID2 BILL_DT CHANNEL OPPTY_CMPGN_CD CAMPAIGN_DESC CMPGN_TYP OPPTY_SUBTYP_ID OPPTY_SUBTYP_CD2 
BILL_TYPE RATE_BILLED SRC_CD3 BO_CLIENT DCS_CLIENT CLNT_AGGR_LST_NM NON_PBM_CLNT_ID2 EVNT_REL_ID ERROR_CD2 QL_BENE_ID PRSN_NBR2 
EXT_MEMBER_ID CHNL_REC_STATUS CHNL_REC_CREATED_DT CHNL_REC_DLVRY_DT CHNL_REC_DISPOSITION_DT ERROR_CD3 ERROR_DESC2 ACCT_TYP_CD2 
EVNT_PROD_ID PROD_ID WAIVR_CMPGN_EFF_DT WAIVR_CMPGN_EXP_DT WAIVR_DSC_TX WAIVR_CLM_SRC_XREF_ID REC_CRTE_PROC_ID REC_CRTE_TRANS_ID 
REC_CRTE_TS REC_CRTE_USER_ID REC_SRC_FILE_NM REC_UPD_PROC_ID REC_UPD_TRANS_ID REC_UPD_TS REC_UPD_USER_ID ;
run;


data y;
set Cpl_1_20220618000123; 
if ( missing(EPH_LINK_ID) or  missing(PRSN_SSK_4) or  missing(EDW_MBR_GID)) and (missing(SPCLT_PTNT_ID)) and (missing(SPCLT_PTNT_GID)) ;
keep  

EPH_LINK_ID PRSN_SSK_4 EDW_MBR_GID PRTC_ID SPCLT_PTNT_ID SPCLT_PTNT_GID

CLT_NM CLT_LEVEL_1 CLT_LEVEL_2 CLT_LEVEL_3 

PRSN_SSK_1 PRSN_SSK_2 PRSN_SSK_3 PRSN_SSK_4 

PTNT_PHONE1_NBR PTNT_EMAIL_ADDR_TX 

PTNT_FIRST_NM
PTNT_MIDDLE_NM
PTNT_LAST_NM
PTNT_BRTH_DT
PTNT_GNDR_CD 
PTNT_ADDR_LINE1_TX 
PTNT_CITY_TX
PTNT_STATE_CD
PTNT_ZIP_CD
PTNT_ZIP_SFX_CD
PTNT_COUNTRY_CD
PTNT_POSTAL_CD

 ;
run;

**/


%macro doit;

			data qc_populate;
			set Cpl_1_20220618000123b; 
			if ( missing(EPH_LINK_ID) or  missing(PRSN_SSK_4) and length(EDW_MBR_GID) > 0 ) and (missing(SPCLT_PTNT_ID)) and (missing(SPCLT_PTNT_GID)) ; 
			run;
			
			data qc_populate;
			set qc_populate;
			if length(EDW_MBR_GID) > 0;
			run;
			
			%let qc_populate = 0;
			
			proc sql noprint;
			select count(*) into: qc_populate separated by ''
			from qc_populate;
			quit;
			
			%put NOTE: qc_populate = &qc_populate. ;
			
			%if &qc_populate. = 0 %then %do;
				%put NOTE: All data elements are populated;
			%end;
			%else %do;
			
				%put NOTE: Missing data elements are populated - fix with EDW_MBR_GID;

				proc sql noprint;
				select edw_mbr_gid into:  edw_mbr_gid separated by ','
				from qc_populate;
				quit;

				proc sql; 
				connect to teradata as tera(server=&c_s_server. user=&td_id. password="&td_pw");
				create table _members as
				select * from connection to tera(

					select 
					to_char(mbr_acct_gid) as EDW_MBR_GID,  
					to_char(eph_id) as CTT_EPH_LINK_ID,
					ql_bnfcy_id  as CTT_PRTC_ID, 
					lvl1_acct_id as CTT_PRSN_SSK_1, 
					lvl2_acct_id as CTT_PRSN_SSK_2, 
					lvl3_acct_id as CTT_PRSN_SSK_3,
					mbr_acct_id  as CTT_PRSN_SSK_4, 
					mbr_brth_dt  as CTT_PTNT_BRTH_DT, 	  
					mbr_frst_nm  as CTT_PTNT_FIRST_NM, 
					mbr_last_nm  as CTT_PTNT_LAST_NM,
					addr_line1   as CTT_PTNT_ADDR_LINE1_TX, 
					addr_city_nm as CTT_PTNT_CITY_TX, 
					addr_st_abbr_cd as CTT_PTNT_STATE_CD, 
					addr_zip5_cd as CTT_PTNT_ZIP_CD, 
					gndr_cd      as CTT_PTNT_GNDR_CD,
					lvl1_acct_nm as CTT_CLT_NM, 
					lvl1_acct_id as CTT_CLT_LEVEL_1, 
					lvl2_acct_id as CTT_CLT_LEVEL_2, 
					lvl3_acct_id as CTT_CLT_LEVEL_3
					from dwu_edw.v_mbr_acct_denorm a,
					     dwu_edw.v_clnt_acct_denorm b
					where a.lvl3_acct_gid = b.lvl3_acct_gid
					and mbr_acct_gid in (&edw_mbr_gid.)

				) ;
				quit;

				proc sort data = _members;
				by EDW_MBR_GID;
				run;

				proc datasets library=work;
				 modify Cpl_1_20220618000123b;
				 index create EDW_MBR_GID; 
				 run;
				quit;

				data yy;
				merge Cpl_1_20220618000123b (in=a) _members (in=b);
				by EDW_MBR_GID; 
				if ( missing(EPH_LINK_ID) or  missing(PRSN_SSK_4) and length(EDW_MBR_GID) > 0 ) and (missing(SPCLT_PTNT_ID)) and (missing(SPCLT_PTNT_GID)) then do;

					EPH_LINK_ID=CTT_EPH_LINK_ID;  
					PRTC_ID=CTT_PRTC_ID;
					PRSN_SSK_1=CTT_PRSN_SSK_1;
					PRSN_SSK_2=CTT_PRSN_SSK_2;
					PRSN_SSK_3=CTT_PRSN_SSK_3;
					PRSN_SSK_4=CTT_PRSN_SSK_4;
					CLT_NM=CTT_CLT_NM;
					CLT_LEVEL_1=CTT_CLT_LEVEL_1; 
					CLT_LEVEL_2=CTT_CLT_LEVEL_2;
					CLT_LEVEL_3=CTT_CLT_LEVEL_3;

					PTNT_FIRST_NM=CTT_PTNT_FIRST_NM; 
					PTNT_LAST_NM=CTT_PTNT_LAST_NM;
					PTNT_BRTH_DT=put(CTT_PTNT_BRTH_DT,yymmdd10.);
					PTNT_GNDR_CD=CTT_PTNT_GNDR_CD; 
					PTNT_ADDR_LINE1_TX=CTT_PTNT_ADDR_LINE1_TX; 
					PTNT_CITY_TX=CTT_PTNT_CITY_TX;
					PTNT_STATE_CD=CTT_PTNT_STATE_CD;
					PTNT_ZIP_CD=CTT_PTNT_ZIP_CD;

				end;
				drop  CTT_: ;
				run;  
				
			%end;

%mend doit;
%doit;

 
